HotelProject.Web/Controllers/GuestsController.cs
using AutoMapper;
using HotelProject.Data;
using HotelProject.Models;
using HotelProject.Models.DTOS;
using HotelProject.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace HotelProject.Web.Controllers
{
    public class GuestsController : Controller
    {
        private readonly IGuestRepository _guestRepository;
        private readonly IGuestReservationRepository _guestReservationRepository;
        private readonly IReservationRepository _reservationRepository;
        private readonly IMapper _mapper;
        private readonly ApplicationDbContext _context;

        public GuestsController(IGuestRepository guestRepository, IGuestReservationRepository guestReservationRepository, IReservationRepository reservationRepository, IMapper mapper, ApplicationDbContext context)
        {
            _guestRepository = guestRepository;
            _guestReservationRepository = guestReservationRepository;
            _reservationRepository = reservationRepository;
            _mapper = mapper;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<GuestReservation> rawData = await _guestReservationRepository.GetAllAsync(includePropeties: "Guest,Reservation");
            List<GuestReservationDto> result = _mapper.Map<List<GuestReservationDto>>(rawData);

            return View(result);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(GuestReservationForCreatingDto model)
        {
            Guest newGuest = _mapper.Map<Guest>(model);
            Reservation newReservation = _mapper.Map<Reservation>(model);

            await _guestRepository.AddAsync(newGuest);
            await _reservationRepository.AddAsync(newReservation);

            await _context.SaveChangesAsync();

            var newGuestFromDb = await _guestRepository.GetAsync(x => x.PersonalNumber == model.PersonalNumber);
            var newReservationFromDb = await _reservationRepository.GetAsync(x => x.CheckInDate == model.CheckInDate && x.CheckOutDate == model.CheckOutDate);

            model.GuestId = newGuestFromDb.Id;
            model.ReservationId = newReservationFromDb.Id;

            await _guestReservationRepository.AddAsync(_mapper.Map<GuestReservation>(model));

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Delete(int id)
        {
            var result = await _guestReservationRepository.GetAsync(x => x.Id == id, includePropeties: "Guest,Reservation");
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePOST(int id, int guestId, int reservationId)
        {
            var guestReservationToRemove = await _guestReservationRepository.GetAsync(filter: x => x.Id == id);
            var guestToRemove = await _guestRepository.GetAsync(filter: x => x.Id == guestId);
            var reservationToRemove = await _reservationRepository.GetAsync(filter: x => x.Id == reservationId);

            _guestReservationRepository.Remove(guestReservationToRemove);
            _guestRepository.Remove(guestToRemove);
            _reservationRepository.Remove(reservationToRemove);

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var rawData = await _guestReservationRepository.GetAsync(x => x.Id == id, includePropeties: "Guest,Reservation");
            GuestWithReservationForUpdatingDto result = _mapper.Map<GuestWithReservationForUpdatingDto>(rawData);
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePOST(GuestWithReservationForUpdatingDto model)
        {
            await _guestReservationRepository.Update(_mapper.Map<GuestReservation>(model));
            await _guestRepository.Update(_mapper.Map<Guest>(model));
            await _reservationRepository.Update(_mapper.Map<Reservation>(model));

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

HotelProject.Web/Views/Guests/Create.cshtml
@model GuestReservationForCreatingDto
@{
    ViewData["Title"] = "ახალი სტუმარი";
}

<form asp-controller="Guests" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="FirstName">სახელი</label>
        <input class="form-control" asp-for="FirstName" />
    </div>
    <div class="mb-3">
        <label asp-for="LastName">გვარი</label>
        <input class="form-control" asp-for="LastName" />
    </div>
    <div class="mb-3">
        <label asp-for="PersonalNumber">პირადი ნომერი</label>
        <input class="form-control" asp-for="PersonalNumber" />
    </div>
    <div class="mb-3">
        <label asp-for="PhoneNumber">ტელეფონის ნომერი</label>
        <input class="form-control" asp-for="PhoneNumber" />
    </div>
    <div class="mb-3">
        <div class="row">
            <div class="col">
                <label asp-for="CheckInDate">შემოსვლის თარიღი</label>
                <input class="form-control" asp-for="CheckInDate" />
            </div>
            <div class="col">
                <label asp-for="CheckOutDate">გასვლის თარიღი</label>
                <input class="form-control" asp-for="CheckOutDate" />
            </div>
        </div>
    </div>
    <div class="mb-3">
        <input type="submit" class="btn btn-success" value="დამატება" />
    </div>
</form>

HotelProject.Web/Views/Guests/Delete.cshtml
@model GuestReservation
<form asp-controller="Guests" asp-action="DeletePOST" method="post">
    <input hidden asp-for="Id" />
    <input hidden asp-for="GuestId" />
    <input hidden asp-for="ReservationId" />
    <div class="mb-3">
        <label class="form-label">@Model.Guest.FirstName @Model.Guest.LastName</label>
        <input class="form-control" asp-for="GuestId" disabled />
    </div>
    <div class="mb-3">
        <label class="form-label">Check in/out: @Model.Reservation.CheckInDate - @Model.Reservation.CheckOutDate</label>
        <input class="form-control" asp-for="ReservationId" disabled />
    </div>
    <div class="mb-3">
        <input type="submit" class="btn btn-danger" value="წაშლა" />
    </div>
</form>

HotelProject.Web/Views/Guests/Index.cshtml
@model List<GuestReservationDto>
@{
    ViewData["Title"] = "სტუმრები - ჯავშნები";
}

<div class="row">
    <a class="btn btn-success w-25 btn btn-primary" asp-controller="Guests" asp-action="Create">ახალი სტუმარი</a>
</div>
<div class="row">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>სახელი</th>
                <th>ტელეფონი</th>
                <th>ვადა</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var gr in Model)
            {
                <tr>
                    <td>@gr.FirstName @gr.LastName</td>
                    <td>@gr.PhoneNumber</td>
                    <td>@gr.CheckOutDate</td>
                    <td>
                        <a class="btn btn-danger" asp-controller="Guests" asp-action="Delete" asp-route-id="@gr.Id">წაშლა</a>
                        <a class="btn btn-info" asp-controller="Guests" asp-action="Update" asp-route-id="@gr.Id">განახლება</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

HotelProject.Web/Views/Guests/Update.cshtml
@model GuestWithReservationForUpdatingDto
@{
    ViewData["Title"] = "სტუმრის განახლება";
}
<form asp-controller="Guests" asp-action="UpdatePOST" method="post">
    <input hidden asp-for="Id" />
    <input hidden asp-for="GuestId" />
    <input hidden asp-for="ReservationId" />
    <div class="mb-3">
        <label asp-for="FirstName">სახელი</label>
        <input class="form-control" asp-for="FirstName" />
    </div>
    <div class="mb-3">
        <label asp-for="LastName">გვარი</label>
        <input class="form-control" asp-for="LastName" />
    </div>
    <div class="mb-3">
        <label asp-for="PersonalNumber">პირადი ნომერი</label>
        <input class="form-control" asp-for="PersonalNumber" />
    </div>
    <div class="mb-3">
        <label asp-for="PhoneNumber">ტელეფონის ნომერი</label>
        <input class="form-control" asp-for="PhoneNumber" />
    </div>
    <div class="mb-3">
        <div class="row">
            <div class="col">
                <label asp-for="CheckInDate">შემოსვლის თარიღი</label>
                <input class="form-control" asp-for="CheckInDate" />
            </div>
            <div class="col">
                <label asp-for="CheckOutDate">გასვლის თარიღი</label>
                <input class="form-control" asp-for="CheckOutDate" />
            </div>
        </div>
    </div>
    <div class="mb-3">
        <input type="submit" class="btn btn-success" value="განახლება" />
    </div>
</form>