HotelProject.Web/Controllers/ManagersController.cs
using HotelProject.Data;
using HotelProject.Models;
using HotelProject.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace HotelProject.Web.Controllers
{
    public class ManagersController : Controller
    {
        private readonly IManagerRepository _managerRepository;
        private readonly IHotelRepository _hotelRepository;
        private readonly ApplicationDbContext _context;
        public ManagersController(IManagerRepository managerRepository, IHotelRepository hotelRepository, ApplicationDbContext context)
        {
            _managerRepository = managerRepository;
            _hotelRepository = hotelRepository;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _managerRepository.GetAllAsync(includePropeties: "Hotel");
            return View(result);
        }

        public async Task<IActionResult> Create()
        {
            var hotels = await _hotelRepository.GetAllAsync(x => x.Manager == null);
            ViewBag.HotelsWithoutManagers = new SelectList(hotels, "Id", "Name");

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(Manager model)
        {
            await _managerRepository.AddAsync(model);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var result = await _managerRepository.GetAsync(x => x.Id == id, includePropeties: "Hotel");
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePOST(int id)
        {
            var result = await _managerRepository.GetAsync(x => x.Id == id, includePropeties: "Hotel");

            _managerRepository.Remove(result);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Update(int id)
        {
            var result = await _managerRepository.GetAsync(x => x.Id == id, includePropeties: "Hotel");
            var hotels = await _hotelRepository.GetAllAsync(x => x.Manager == null);
            ViewBag.HotelsWithoutManagers = new SelectList(hotels, "Id", "Name");

            return View(result);
        }


        [HttpPost]
        public async Task<IActionResult> UpdatePOST(Manager model)
        {
            await _managerRepository.Update(model);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

    }
}

HotelProject.Web/Views/Managers/Create.cshtml
@model Manager
@{
    ViewData["Title"] = "ახალი მენეჯერის დამატება";
}
<form asp-controller="Managers" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="FirstName">სახელი</label>
        <input class="form-control" asp-for="FirstName" />
    </div>
    <div class="mb-3">
        <label asp-for="LastName">გვარი</label>
        <input class="form-control" asp-for="LastName" />
    </div>
    <div class="mb-3">
        <label asp-for="HotelId">სასტუმრო</label>
        <select asp-for="HotelId" asp-items="ViewBag.HotelsWithoutManagers" class="form-control"></select>
    </div>
    <div class="mb-3">
        <input type="submit" class="btn btn-success" value="დამატება" />
    </div>
</form>

HotelProject.Web/Views/Managers/Delete.cshtml
@model Manager
@{
    ViewData["Title"] = "მენეჯერის წაშლა";
}
<form asp-controller="Managers" asp-action="DeletePOST" method="post">
    <input hidden asp-for="Id" />
    <div class="mb-3">
        <input class="form-control" asp-for="FirstName" disabled />
    </div>
    <div class="mb-3">
        <input class="form-control" asp-for="LastName" disabled />
    </div>
    <div class="mb-3">
        <input class="form-control" asp-for="Hotel.Name" disabled />
    </div>
    <div class="mb-3">
        <input type="submit" class="btn btn-danger" value="წაშლა" />
    </div>
</form>

HotelProject.Web/Views/Managers/Index.cshtml
@model List<Manager>
<div class="row">
    <a class="btn btn-success w-25 btn btn-primary" asp-controller="Managers" asp-action="Create">ახალი მენეჯერი</a>
</div>
<div class="row">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>სახელი</th>
                <th>სასტუმრო</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var manager in Model)
            {
                <tr>
                    <td>@manager.FirstName @manager.LastName</td>
                    <td>@manager.Hotel.Name</td>
                    <td>
                        <a class="btn btn-danger" asp-controller="Managers" asp-action="Delete" asp-route-id="@manager.Id">წაშლა</a>
                        <a class="btn btn-info" asp-controller="Managers" asp-action="Update" asp-route-id="@manager.Id">განახლება</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

HotelProject.Web/Views/Managers/Update.cshtml
@model Manager
@{
    ViewData["Title"] = "მენეჯერის განახლება";
}
<form asp-controller="Managers" asp-action="UpdatePOST" method="post">
    <input hidden asp-for="Id" />
    <div class="mb-3">
        <label asp-for="FirstName">სახელი</label>
        <input class="form-control" asp-for="FirstName" />
    </div>
    <div class="mb-3">
        <label asp-for="LastName">გვარი</label>
        <input class="form-control" asp-for="LastName" />
    </div>
    <div class="mb-3">
        <label asp-for="HotelId">სასტუმრო</label>
        <select asp-for="HotelId" asp-items="ViewBag.HotelsWithoutManagers" class="form-control"></select>
    </div>
    <div class="mb-3">
        <input type="submit" class="btn btn-success" value="განახლება" />
    </div>
</form>