HotelProject.Web/Controllers/HotelsController.cs
using HotelProject.Data;
using HotelProject.Models;
using HotelProject.Repository.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HotelProject.Web.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class HotelsController : Controller
    {
        private readonly IHotelRepository _hotelRepository;
        private readonly ApplicationDbContext _context;
        public HotelsController(IHotelRepository hotelRepository, ApplicationDbContext context)
        {
            _hotelRepository = hotelRepository;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _hotelRepository.GetAllAsync();
            return View(result);
        }


        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(Hotel model)
        {
            await _hotelRepository.AddAsync(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Delete(int id)
        {
            var result = await _hotelRepository.GetAsync(x => x.Id == id);
            return View(result);
        }


        [HttpPost]
        public async Task<IActionResult> DeletePOST(int id)
        {
            var result = await _hotelRepository.GetAsync(x => x.Id == id);

            _hotelRepository.Remove(result);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(int id)
        {
            var result = await _hotelRepository.GetAsync(x => x.Id == id);
            return View(result);
        }


        [HttpPost]
        public async Task<IActionResult> UpdatePOST(Hotel model)
        {
            await _hotelRepository.Update(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

HotelProject.Web/Views/Hotels/Create.cshtml
@model Hotel
@{
    ViewData["Title"] = "ახალი სასტუმროს დამატება";
}
<form asp-controller="Hotels" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Name">დასახელება</label>
        <input class="form-control" asp-for="Name" />
    </div>
    <div class="mb-3">
        <label asp-for="Rating">რეიტნგი</label>
        <input class="form-control" asp-for="Rating" />
    </div>
    <div class="mb-3">
        <label asp-for="Country">ქვეყანა</label>
        <input class="form-control" asp-for="Country" />
    </div>
    <div class="mb-3">
        <label asp-for="City">ქალაქი</label>
        <input class="form-control" asp-for="City" />
    </div>
    <div class="mb-3">
        <label asp-for="PhyisicalAddress">მისამართი</label>
        <input class="form-control" asp-for="PhyisicalAddress" />
    </div>
    <div class="mb-3">
        <input type="submit" class="btn btn-success" value="დამატება" />
    </div>
</form>

HotelProject.Web/Views/Hotels/Delete.cshtml
@model Hotel
@{
    ViewData["Title"] = "სასტუმროს წაშლა";
}
<form asp-controller="Hotels" asp-action="DeletePOST" method="post">
    <input hidden asp-for="Id" />
    <div class="mb-3">
        <input class="form-control" asp-for="Name" disabled />
    </div>
    <div class="mb-3">
        <input class="form-control" asp-for="Rating" disabled />
    </div>
    <div class="mb-3">
        <input class="form-control" asp-for="Country" disabled />
    </div>
    <div class="mb-3">
        <input class="form-control" asp-for="City" disabled />
    </div>
    <div class="mb-3">
        <input class="form-control" asp-for="PhyisicalAddress" disabled />
    </div>
    <div class="mb-3">
        <input type="submit" class="btn btn-danger" value="წაშლა" />
    </div>
</form>

HotelProject.Web/Views/Hotels/Index.cshtml
@model List<Hotel>

<div class="row">
    <a class="btn btn-success w-25 btn btn-primary" asp-controller="Hotels" asp-action="Create">ახალი სასტუმრო</a>
</div>
<div class="row">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>სახელი</th>
                <th>რეიტინგი</th>
                <th>ქვეყანა</th>
                <th>ქალაქი</th>
                <th>მისამართი</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var hotel in Model)
            {
                <tr>
                    <td>@hotel.Name</td>
                    <td>@hotel.Rating</td>
                    <td>@hotel.Country</td>
                    <td>@hotel.City</td>
                    <td>@hotel.PhyisicalAddress</td>
                    <td>
                        <a class="btn btn-danger" asp-controller="Hotels" asp-action="Delete" asp-route-id="@hotel.Id">წაშლა</a>
                        <a class="btn btn-info" asp-controller="Hotels" asp-action="Update" asp-route-id="@hotel.Id">განახლება</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

HotelProject.Web/Views/Hotels/Update.cshtml
@model Hotel
@{
    ViewData["Title"] = "სასტუმროს განახლება";
}
<form asp-controller="Hotels" asp-action="UpdatePOST" method="post">
    <input hidden asp-for="Id" />
    <div class="mb-3">
        <label asp-for="Name">დასახელება</label>
        <input class="form-control" asp-for="Name" />
    </div>
    <div class="mb-3">
        <label asp-for="Rating">რეიტნგი</label>
        <input class="form-control" asp-for="Rating" />
    </div>
    <div class="mb-3">
        <label asp-for="Country">ქვეყანა</label>
        <input class="form-control" asp-for="Country" />
    </div>
    <div class="mb-3">
        <label asp-for="City">ქალაქი</label>
        <input class="form-control" asp-for="City" />
    </div>
    <div class="mb-3">
        <label asp-for="PhyisicalAddress">მისამართი</label>
        <input class="form-control" asp-for="PhyisicalAddress" />
    </div>
    <div class="mb-3">
        <input type="submit" class="btn btn-success" value="განახლება" />
    </div>
</form>